version: '3.9'

services:
  sidetree_prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.yaml'
    volumes:
      - ./did_sidetree.yaml:/tmp/api.yaml:ro
    ports:
      - '4010:4010'

  studio_prism:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.yaml'
    volumes:
      - ./studio.yaml:/tmp/api.yaml:ro
    ports:
      - '8020:4010'

