name: e2e test with docker
description: "E2E test action with docker-compose"
inputs:
  binary-path:
    required: true
    description: "the path of the binary to be tested"
  docker-image:
    required: true
    description: "the name of docker compose override files. check the file in test_resource/overrides/ for the available options"
runs:
  using: composite
  steps:
    - name: (setup) copy binary for e2e tests
      shell: bash
      run: cp ${{ inputs.binary-path }} ./test_resource/

    - name: (setup) pull docker images
      shell: bash
      run: docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml pull -q

    - name: (run) run mock server
      shell: bash
      run: docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e up -d

    - name: (run) e2e tests
      shell: bash
      run: docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e run e2e_runner cargo test

    - name: (run) shutdown agent
      shell: bash
      run: |
        container_id=$(docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e ps -q e2e_agent)
        pid=$(docker exec $container_id pgrep -f nodex-agent)
        docker exec $container_id kill -SIGINT $pid
      if: ${{ always() }}

    - name: (run) Check for 'stopped' log message
      shell: bash
      id: check_logs
      run: |
        if docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e logs e2e_agent | grep -q "stopped"; then
          echo "::set-output name=stopped_found::true"
        else
          echo "::set-output name=stopped_found::false"
        fi

    - name: (run)  Verify process is not running in e2e_agent
      shell: bash
      if: steps.check_logs.outputs.stopped_found == 'true'
      run: |
        container_id=$(docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e ps -q e2e_agent)
        if ! docker exec $container_id pgrep -f /tmp/nodex-agent; then
          echo "Process not found, as expected."
        else
          echo "Process is still running, which is not expected."
          exit 1
        fi

    - name: (run) show log of agent
      shell: bash
      run: docker compose -f test_resource/compose.yaml -f test_resource/overrides/${{ inputs.docker-image }}.yaml --profile e2e logs e2e_agent
      if: ${{ always() }}
