name: release
description: ""
inputs:
  github-token:
    required: true
    description: ""
  use-cache:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (setup) environment
      uses: ./.github/actions/shared

    - name: (cache) rust
      if: ${{ inputs.use-cache == 'true' }}
      uses: Swatinem/rust-cache@v2

    - name: (install) cargo-semver
      shell: bash
      run: cargo install cargo-semver --vers 1.0.0-alpha.3

    - name: (run) commit analyzer
      id: commit_analyzer
      uses: ./.github/actions/commit-analyzer

    - name: (run) bump up
      shell: bash
      run: cargo semver set "${{ steps.commit_analyzer.outputs.version }}"

    - name: (run) create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: "${{ inputs.github-token }}"
        commit-message: "chore(release): bump up to ${{ steps.commit_analyzer.outputs.version }}"
        committer: "${{ github.actor }} [bot] <${{ github.actor }}@users.noreply.github.com>"
        branch: release/release
        branch-suffix: random
        title: "[release] bump up to ${{ steps.commit_analyzer.outputs.version }}"
        body: |
          [release] bump up to ${{ steps.commit_analyzer.outputs.version }}

          This PullRequest was automatically created by GitHub Workflow. Please review and then accept or reject.

          - [ ] Version number is correct ?
          - [ ] `Cargo.toml` and `Cargo.lock` files included in pull request ?
        delete-branch: true
        assignees: vaachii
        reviewers: vaachii
        labels: release