name: shared
description: ""
runs:
  using: composite
  steps:
    - name: (install) rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly

    - name: (install) nodejs toolchain
      uses: actions/setup-node@v3

    - name: (config) set nightly toolchain to default
      shell: bash
      run: rustup default nightly

    - name: (install) rust-src
      shell: bash
      run: rustup component add rust-src

    - name: (install) clippy
      shell: bash
      run: rustup component add clippy