name: prepare
description: ""
inputs:
  github-token:
    required: true
    description: ""
runs:
  using: composite
  steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    # - name: (check) conventional commits
    #   uses: webiny/action-conventional-commits@v1.0.3