name: default-pipeline

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) prepare
      uses: ./.github/actions/prepare
      with:
        github-token: ${{ env.GITHUB_TOKEN }}

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    needs: [ prepare ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) build
      uses: ./.github/actions/build
      with:
        os: ${{ matrix.os }}
        use-cache: true
        github-token: ${{ env.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: [ prepare ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) test
      uses: ./.github/actions/test
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        use-cache: true