name: publish-pipeline

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) lint
      uses: ./.github/actions/lint
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        use-cache: true

  test:
    runs-on: ubuntu-latest

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) test
      uses: ./.github/actions/test
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        use-cache: true

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) build
      uses: ./.github/actions/build
      with:
        os: ${{ matrix.os }}
        use-cache: false
        github-token: ${{ env.GITHUB_TOKEN }}

  publish:
    needs: [ lint, test, build ]
    runs-on: ubuntu-latest

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) publish
      uses: ./.github/actions/publish
      with:
        github-token: ${{ env.GITHUB_TOKEN }}

  create-tag:
    runs-on: ubuntu-latest
    needs: [ publish ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) create tag
      uses: ./.github/actions/create-tag
      with:
        github-token: ${{ env.GITHUB_TOKEN }}