name: release-pipeline

on:
  push:
    branches: [ main ]
    tags-ignore:
      - "*"
    paths-ignore:
      - "Cargo.toml"
      - "Cargo.lock"

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) prepare
      uses: ./.github/actions/prepare
      with:
        github-token: ${{ env.GITHUB_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [ prepare ]

    steps:
    - name: (checkout) source code
      uses: actions/checkout@v3

    - name: (run) release
      uses: ./.github/actions/release
      with:
        github-token: ${{ env.GITHUB_TOKEN }}
        use-cache: true